// frontend/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  type Rating = 'Too Easy' | 'Just Right' | 'Too Hard';
  let story = '';
  let loading = false;
  let error: string | null = null;
  let hasRated = false;

  const API_URL = 'http://localhost:8000';

  async function fetchStory(last_rating?: Rating) {
    loading = true;
    error = null;
    hasRated = false;
    try {
      const res = await fetch(`${API_URL}/generate_story`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ last_rating }),
      });
      if (!res.ok) throw new Error('Failed to fetch story');
      const data = await res.json();
      story = data.story;
    } catch (e) {
      error = e instanceof Error ? e.message : 'Unknown error';
    } finally {
      loading = false;
    }
  }

  function handleRating(rating: Rating) {
    hasRated = true;
    if (rating === 'Just Right') return;
    fetchStory(rating);
  }

  onMount(() => {
    fetchStory();
  });
</script>

<main style="max-width: 900px; margin: 0 auto; padding: 2rem 1rem; font-family: system-ui, sans-serif;">
  {#if loading}
    <p>Loading...</p>
  {:else if error}
    <p style="color: #c00;">{error}</p>
  {:else}
    <div style="white-space: pre-line; font-size: 1.2rem; color: #222; text-align: left; margin-bottom: 2rem;">
      {story}
    </div>
  {/if}
  <div style="display: flex; gap: 1rem; margin-bottom: 1.5rem;">
    <button
      on:click={() => handleRating('Too Easy')}
      disabled={loading || hasRated}
      style="padding: 0.6rem 1.2rem;"
    >Too Easy</button>
    <button
      on:click={() => handleRating('Just Right')}
      disabled={loading || hasRated}
      style="padding: 0.6rem 1.2rem;"
    >Just Right</button>
    <button
      on:click={() => handleRating('Too Hard')}
      disabled={loading || hasRated}
      style="padding: 0.6rem 1.2rem;"
    >Too Hard</button>
  </div>
  {#if hasRated}
    <p style="color: #3366cc;">Thank you for your feedback!</p>
  {/if}
</main>

// frontend/src/App.tsx
import React, { useState, useEffect } from 'react';

const API_URL = 'http://localhost:8000';
type Rating = 'Too Easy' | 'Just Right' | 'Too Hard';

function App() {
  const [story, setStory] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [hasRated, setHasRated] = useState<boolean>(false);

  useEffect(() => {
    fetchStory();
  }, []);

  const fetchStory = async (last_rating?: Rating) => {
    setLoading(true);
    setError(null);
    setHasRated(false);
    try {
      const res = await fetch(`${API_URL}/generate_story`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ last_rating }),
      });
      if (!res.ok) throw new Error('Failed to fetch story');
      const data = await res.json();
      setStory(data.story);
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('Unknown error');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleRating = (rating: Rating) => {
    setHasRated(true);
    if (rating === 'Just Right') return;
    fetchStory(rating);
  };

  return (
    <div style={{ margin: 0, padding: 0 }}>
      <style>{`
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
      `}</style>
      {loading && <div>Loading...</div>}
      {error && <div style={{ color: 'red' }}>{error}</div>}
      {!loading && !error && <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{story}</pre>}
      {hasRated && <div>Thank you for your feedback!</div>}
      <div style={{ marginTop: '1em' }}>
        {(['Too Easy', 'Just Right', 'Too Hard']).map((rating) => (
          <button
            key={rating}
            onClick={() => handleRating(rating as Rating)}
            disabled={loading || hasRated}
            style={{ marginRight: 8 }}
          >
            {rating}
          </button>
        ))}
      </div>
    </div>
  );
}

export default App;
